// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: grpc/proto/insulter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// InsulterClient is the client API for Insulter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InsulterClient interface {
	Insult(ctx context.Context, in *Value_IN, opts ...grpc.CallOption) (*Value_OUT, error)
}

type insulterClient struct {
	cc grpc.ClientConnInterface
}

func NewInsulterClient(cc grpc.ClientConnInterface) InsulterClient {
	return &insulterClient{cc}
}

func (c *insulterClient) Insult(ctx context.Context, in *Value_IN, opts ...grpc.CallOption) (*Value_OUT, error) {
	out := new(Value_OUT)
	err := c.cc.Invoke(ctx, "/insulter.insulter/Insult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsulterServer is the server API for Insulter service.
// All implementations should embed UnimplementedInsulterServer
// for forward compatibility
type InsulterServer interface {
	Insult(context.Context, *Value_IN) (*Value_OUT, error)
}

// UnimplementedInsulterServer should be embedded to have forward compatible implementations.
type UnimplementedInsulterServer struct {
}

func (UnimplementedInsulterServer) Insult(context.Context, *Value_IN) (*Value_OUT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insult not implemented")
}

// UnsafeInsulterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsulterServer will
// result in compilation errors.
type UnsafeInsulterServer interface {
	mustEmbedUnimplementedInsulterServer()
}

func RegisterInsulterServer(s grpc.ServiceRegistrar, srv InsulterServer) {
	s.RegisterService(&Insulter_ServiceDesc, srv)
}

func _Insulter_Insult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Value_IN)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsulterServer).Insult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/insulter.insulter/Insult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsulterServer).Insult(ctx, req.(*Value_IN))
	}
	return interceptor(ctx, in, info, handler)
}

// Insulter_ServiceDesc is the grpc.ServiceDesc for Insulter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Insulter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insulter.insulter",
	HandlerType: (*InsulterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insult",
			Handler:    _Insulter_Insult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/proto/insulter.proto",
}
